version: '3.8'
services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - REGION=${REGION}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}
    networks:
      - backend
networks:
  backend:
    driver: bridge